# Generated by Django 5.2.8 on 2025-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement_profile_avg_daily_emission_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('iot', 'IoT Device'), ('chatbot_pending', 'Chatbot (Pending)'), ('chatbot_processed', 'Chatbot (Processed)')], default='manual', max_length=20),
        ),
    ]
