# Generated by Django 5.2.6 on 2025-12-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailverification_remove_profile_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='reward_xp',
            new_name='xp_reward',
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Home Energy'), ('food', 'Food'), ('consumption', 'Purchases'), ('waste', 'Waste'), ('community', 'Community')], default='transport', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.achievement'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='rules',
            field=models.TextField(default='No specific rules.', help_text='Bullet points of rules'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='total_days',
            field=models.IntegerField(default=7),
        ),
    ]
