# Generated by Django 5.2.8 on 2025-12-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_reward_xp_challenge_xp_reward_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='xp_reward',
            new_name='reward_xp',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='reward_badge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='total_days',
        ),
    ]
